language: elixir
script:
  - mix test.setup
  - mix test
matrix:
  include:
    # - otp_release: 19.3
    #   elixir: 1.7.4
    # - otp_release: 21.2
    #   elixir: 1.8.2
    - otp_release: 22.0
      elixir: 1.9.0
services:
  - postgresql
env:
  - SECRET_KEY_BASE="hdJCKNw5/2H3Kqig0iOlh5iz2JyIaGJsSgreZmu+6fS/Jd281/E9Fg1PV+7L/+DH" TEST_DATABASE_URL="postgresql://postgres:postgres@localhost:5432/institute_test" DATABASE_URL="postgresql://postgres:postgres@localhost:5432/institute_test" PORT=4002 REPO_SSL="false" DISTILLERY_COOKIE="y/yyfSW7yjRkzptqeyhejewYWXtoE3NCIacIISUVxKavpF9wbjV8U9NBDv7vn+uw" SESSION_SIGNING_SALT="test du sel"
